<a href="https://colab.research.google.com/github/forbiddenvelocity/Learning-Pytorch/blob/main/LearningPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors


Tensor - A multidimensional matrix containing elements of a single data type.

In [2]:
import torch

#torch.empty(size): uninitiallized
x = torch.empty(1) #scalar
print("empty(1):", x)
x = torch.empty(3) #vector
print("empty(3):", x)
x = torch.empty(2, 3) #matrix
print("empty(2,3):", x)
x = torch.empty(2, 2, 3 ) #tensor
print("empty(2,2,3):", x)
x = torch.rand(5, 3) #random matrix
print("rand(5,3):", x)

#torch.zeros(size), fill with 0s
#torch.ones(size), fill with 1s
x = torch.zeros(5, 3)
print("zeros(5,3):", x)
x = torch.ones(5, 3)
print("ones(5,3):", x)

empty(1): tensor([3.1278e-24])
empty(3): tensor([ 1.6393e+03,  3.1109e-41, -1.7811e+02])
empty(2,3): tensor([[1.6399e+03, 3.1109e-41, 1.6397e+03],
        [3.1109e-41, 1.1210e-43, 0.0000e+00]])
empty(2,2,3): tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])
rand(5,3): tensor([[0.6482, 0.2828, 0.9649],
        [0.3674, 0.3985, 0.9481],
        [0.9759, 0.4661, 0.2474],
        [0.1687, 0.1231, 0.8295],
        [0.0983, 0.6325, 0.7223]])
zeros(5,3): tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
ones(5,3): tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
#size
print("size", x.size())  #x.size(0)
print("shape", x.shape)  #x.shape[0]
print("dim", x.dim())  #x.dim()

size torch.Size([5, 3])
shape torch.Size([5, 3])
dim 2


In [ ]:
#data type
print(x.dtype)

x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

#check data type
print(x.dtype)

torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [ ]:
# construct from data
x = torch.tensor([5.5, 3])
print(x, x.dtype)

tensor([5.5000, 3.0000]) torch.float32


In [ ]:
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)
#requires_grad argument
#This tells pytorch that it will need to calculate the gradietns for this tensor
#later in the optimization steps, this is a variable in your model that you want to optimize

tensor([5.5000, 3.0000], requires_grad=True)


# Operations with Tensors

In [ ]:
x = torch.ones(2,2)
y = torch.rand(2,2)

z = x + y #element wise addition
# or torch.add(x,y)
# y.add_(x)

print(x)
print(y)
print(z)



tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3551, 0.3221],
        [0.0142, 0.6702]])
tensor([[1.3551, 1.3221],
        [1.0142, 1.6702]])


In [ ]:
#subtraction
z = x - y
z = torch.sub(x,y)

#multiplication
z = torch.mul(x,y)
z = x * y

#division
z = torch.div(x,y)
z = torch.div(x,y)

In [ ]:
# slicing
x = torch.rand(5,3)
print(x)
print("x[:, 0]", x[:, 0]) # all rows, column 0
print("x[1, :]", x[1, :]) # row 1, all columns
print(x[1, 1]) # element at row 1, column 1

print("x[1,1].item()", x[1,1].item())

tensor([[0.9685, 0.5182, 0.8885],
        [0.3594, 0.5325, 0.5461],
        [0.5271, 0.1268, 0.9829],
        [0.2516, 0.8708, 0.7997],
        [0.8452, 0.4711, 0.5992]])
x[:, 0] tensor([0.9685, 0.3594, 0.5271, 0.2516, 0.8452])
x[1, :] tensor([0.3594, 0.5325, 0.5461])
tensor(0.5325)
x[1,1].item() 0.5324912667274475


In [3]:
#Reshaping with torch.view()
x = torch.randn(4,4)
print(x)
y = x.view(16)
z = x.view(-1,8)
print(y)
print(z)
print(z.size(), y.size(), z.size())
#

tensor([[ 0.3332, -0.2433, -0.1464, -0.1438],
        [-0.9129, -0.4019,  1.5588,  0.5908],
        [ 1.2441,  1.4796, -0.2553,  0.3944],
        [ 1.4202,  0.1795, -0.2441, -1.1942]])
tensor([ 0.3332, -0.2433, -0.1464, -0.1438, -0.9129, -0.4019,  1.5588,  0.5908,
         1.2441,  1.4796, -0.2553,  0.3944,  1.4202,  0.1795, -0.2441, -1.1942])
tensor([[ 0.3332, -0.2433, -0.1464, -0.1438, -0.9129, -0.4019,  1.5588,  0.5908],
        [ 1.2441,  1.4796, -0.2553,  0.3944,  1.4202,  0.1795, -0.2441, -1.1942]])
torch.Size([2, 8]) torch.Size([16]) torch.Size([2, 8])


# Numpy

In [4]:
a = torch.ones(5)
print(a)

#torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [5]:
# Careful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [6]:
#converting from numpy to torch with .from_numpy(x), or torch.tensor() to copy it
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
c = torch.tensor(a)
print(a)
print(b)
print(c)

a += 1
print(a)
print(b)
print(c)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Note: By default all tensors are created on the CPU but we can also move them to the GPU, or create them directly on the GPU

In [7]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.rand(2,2).to(device) #move tensors to GPU device

x = torch.rand(2,2, device=device) #or directly create them on GPU

# Autograd

The autograd package provides automatic differentiation for all operations on tensors. torch.autograd is an enginer for computing vector-jacobian product. It computes partial derivatives while applying the chain rule.

Set requires_grad = True

In [8]:
import torch

#requires_grad = True -> tracks all operations on the tensors.
x = torch.randn(3, requires_grad=True)
y = x + 2

print(x)
print(y)
print(y.grad_fn)

tensor([ 0.1987, -1.6719,  1.7511], requires_grad=True)
tensor([2.1987, 0.3281, 3.7511], grad_fn=<AddBackward0>)


In [9]:
z = y * y * 3
print(z)
z = z.mean()
print(z)

tensor([14.5027,  0.3229, 42.2114], grad_fn=<MulBackward0>)
tensor(19.0123, grad_fn=<MeanBackward0>)


How to stop a tensor from tracking history?

During training loop when we want to update our weights, or after training during evaluation. These operations should not be part of the gradient computation. To prevent this, we can use:

x.requires_grad_(False)
x.detach()
wrap in with torch.no-grad():

In [10]:
a = torch.randn(2, 2)
b = (a * a).sum()
print(a.requires_grad)
print(b.grad_fn)

# .requires_grad_(..) changes an existing flag in place
a.requires_grad_(True)
b = (a * a).sum()
print(a.requires_grad)
print(b.grad_fn)

False
None
True


In [11]:
# .detach(): get a new tensor with the same content but no gradeint computation:
a = torch.randn(2, 2, requires_grad = True)
b = a.detach()
print(a.requires_grad)
print(b.requires_grad)

True
False


In [12]:
# wrap in 'with torch.no_grad():'
a = torch.randn(2, 2, requires_grad = True)
print(a.requires_grad)
with torch.no_grad():
    b = a * a
    print(b.requires_grad)

True
False


# Gradient Descent Autograd

Linear Regression Example:
𝑓
(
𝑥
)
=
𝑤
⋅
𝑥
+
𝑏

and f(x) = 2 * x


In [13]:
import torch

#linear regression
#f = w * x + b
# f = 2 * x

X = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8, 10, 12, 14, 16], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

def forward(x):
  return w * x

# loss = MSE
def loss(y, y_pred):
  return ((y_pred - y) ** 2).mean()

X_test = 5.0

print(f'Prediction before training: f({X_test}) = {forward(X_test):.3f}')

Prediction before training: f(5.0) = 0.000


In [15]:
#training it
learning_rate = 0.01
n_epochs = 100

for epochs in range(n_epochs):
  #forward pass and loss
  y_pred = forward(X)
  l = loss(Y, y_pred)

  #backward pass
  l.backward()

  with torch.no_grad():
    w -= learning_rate * w.grad

  w.grad.zero_()

  if epochs % 10 == 0:
    print(f'epoch {epochs+1}: w = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after training: f({X_test}) = {forward(X_test):.3f}')

epoch 1: w = 2.040, loss = 102.00000000
epoch 11: w = 2.000, loss = 0.00000011
epoch 21: w = 2.000, loss = 0.00000000
epoch 31: w = 2.000, loss = 0.00000000
epoch 41: w = 2.000, loss = 0.00000000
epoch 51: w = 2.000, loss = 0.00000000
epoch 61: w = 2.000, loss = 0.00000000
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5.0) = 10.000
