<a href="https://colab.research.google.com/github/forbiddenvelocity/Learning-Pytorch/blob/main/LearningPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors


Tensor - A multidimensional matrix containing elements of a single data type.

In [1]:
import torch

#torch.empty(size): uninitiallized
x = torch.empty(1) #scalar
print("empty(1):", x)
x = torch.empty(3) #vector
print("empty(3):", x)
x = torch.empty(2, 3) #matrix
print("empty(2,3):", x)
x = torch.empty(2, 2, 3 ) #tensor
print("empty(2,2,3):", x)
x = torch.rand(5, 3) #random matrix
print("rand(5,3):", x)

#torch.zeros(size), fill with 0s
#torch.ones(size), fill with 1s
x = torch.zeros(5, 3)
print("zeros(5,3):", x)
x = torch.ones(5, 3)
print("ones(5,3):", x)

empty(1): tensor([-1.1906e-29])
empty(3): tensor([-1.1906e-29,  4.5887e-41, -1.1906e-29])
empty(2,3): tensor([[-1.1906e-29,  4.5887e-41, -4.6537e-06],
        [ 3.1001e-41,  0.0000e+00,  3.1001e-41]])
empty(2,2,3): tensor([[[-4.6408e-06,  3.1001e-41, -4.6511e-06],
         [ 3.1001e-41,  1.3452e-43,  0.0000e+00]],

        [[ 1.5695e-43,  0.0000e+00, -1.0785e+10],
         [ 3.1005e-41,  4.1693e-38,  0.0000e+00]]])
rand(5,3): tensor([[0.9540, 0.5816, 0.5827],
        [0.4523, 0.9793, 0.4128],
        [0.7195, 0.4361, 0.8305],
        [0.1733, 0.4481, 0.9642],
        [0.8389, 0.2867, 0.0145]])
zeros(5,3): tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
ones(5,3): tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [2]:
#size
print("size", x.size())  #x.size(0)
print("shape", x.shape)  #x.shape[0]
print("dim", x.dim())  #x.dim()

size torch.Size([5, 3])
shape torch.Size([5, 3])
dim 2


In [3]:
#data type
print(x.dtype)

x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

#check data type
print(x.dtype)

torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [5]:
# construct from data
x = torch.tensor([5.5, 3])
print(x, x.dtype)

tensor([5.5000, 3.0000]) torch.float32


In [7]:
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)
#requires_grad argument
#This tells pytorch that it will need to calculate the gradietns for this tensor
#later in the optimization steps, this is a variable in your model that you want to optimize

tensor([5.5000, 3.0000], requires_grad=True)


# Operations with Tensors

In [8]:
x = torch.ones(2,2)
y = torch.rand(2,2)

z = x + y #element wise addition
# or torch.add(x,y)
# y.add_(x)

print(x)
print(y)
print(z)



tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3551, 0.3221],
        [0.0142, 0.6702]])
tensor([[1.3551, 1.3221],
        [1.0142, 1.6702]])


In [9]:
#subtraction
z = x - y
z = torch.sub(x,y)

#multiplication
z = torch.mul(x,y)
z = x * y

#division
z = torch.div(x,y)
z = torch.div(x,y)

In [10]:
# slicing
x = torch.rand(5,3)
print(x)
print("x[:, 0]", x[:, 0]) # all rows, column 0
print("x[1, :]", x[1, :]) # row 1, all columns
print(x[1, 1]) # element at row 1, column 1

print("x[1,1].item()", x[1,1].item())

tensor([[0.9685, 0.5182, 0.8885],
        [0.3594, 0.5325, 0.5461],
        [0.5271, 0.1268, 0.9829],
        [0.2516, 0.8708, 0.7997],
        [0.8452, 0.4711, 0.5992]])
x[:, 0] tensor([0.9685, 0.3594, 0.5271, 0.2516, 0.8452])
x[1, :] tensor([0.3594, 0.5325, 0.5461])
tensor(0.5325)
x[1,1].item() 0.5324912667274475
